
alias 'x'='clear'
alias 'su+'='sudo -i'
alias 'ls'="/usr/bin/ls ${LS_OPTIONS} -h"
alias 'll'="/usr/bin/ls ${LS_OPTIONS} -hl"
alias 'la'="/usr/bin/ls ${LS_OPTIONS} -hla"
alias 'rm'='rm --preserve-root -v -I'
alias 'chown'='chown --preserve-root -v'
alias 'chmod'='chmod --preserve-root -v'
alias 'mkdir'='mkdir -p -v'
alias 'grep'='grep --color=auto'
alias 'cp'='cp -r -v'
alias 'mv'='mv -v'
alias 'emacs'='emacs -nw'
alias '..'='cd ..'
alias 'fucking'='sudo'
alias 'weather'='curl http://wttr.in/Kyiv?lang=uk' 2> /dev/null
alias 'KILL'='killall -s KILL'

# LOL!!1
alias 'wtf'='dmesg'
alias 'onoz'='cat /var/log/messages'
alias 'rtfm'='man'
alias ':3'='echo'
alias 'visible'='echo'
alias 'invisible'='cat'
alias 'moar'='more'
alias 'tldr'='less'
alias 'alwayz'='tail -f'
alias 'icanhas'='mkdir'
alias 'gimmeh'='touch'
alias 'donotwant'='rm'
alias 'dowant'='cp'
alias 'gtfo'='mv'
alias 'nowai'='chmod'
alias 'hai'='cd'
alias 'iz'='ls'
alias 'plz'='pwd'
alias 'ihasbucket'='df -h'
alias 'inur'='locate'
alias 'iminurbase'='finger'
alias 'btw'='nice'
alias 'obtw'='nohup'
alias 'nomz'='ps auxw'
alias 'nomnom'='killall'
alias 'byes'='exit'
alias 'cya'='reboot'
alias 'kthxbai'='poweroff'
alias 'pwned'='ssh'
alias 'hackzor'='git init'
alias 'rulz'='git push'
alias 'bringz'='git pull'
alias 'chicken'='git add'
alias 'oanward'='git commit -m'
alias 'ooanward'='git commit -am'
alias 'yolo'='git commit -m "$(curl -s https://whatthecommit.com/index.txt)"'
alias 'letcat'='git checkout'
alias 'violenz'='git rebase'

