---
clone:
  git:
    image: plugins/git:next

pipeline:
  lint-shell:
    image: sevoid/linter:plugin
    pull: true
    group: lint
    lint: shell
    files:
      - ".bashrc"
      - ".bash_profile"
      - ".bash_aliases"

  lint-yaml:
    image: sevoid/linter:plugin
    pull: true
    group: lint
    lint: yaml

branches:
  exlude: [ master ]
# vim:set syntax=yaml ts=2 sw=2 et:
